# Generated by Django 3.2 on 2023-02-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Клуб')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='club-images/')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_point', models.PositiveSmallIntegerField(default=0, verbose_name='Счет хозяев')),
                ('guest_point', models.PositiveSmallIntegerField(default=0, verbose_name='Счет гостей')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('red_card', models.PositiveSmallIntegerField(default=0)),
                ('yellow_card', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.PositiveSmallIntegerField(default=0, verbose_name='И')),
                ('win', models.PositiveSmallIntegerField(default=0, verbose_name='В')),
                ('draw', models.PositiveSmallIntegerField(default=0, verbose_name='Н')),
                ('lose', models.PositiveSmallIntegerField(default=0, verbose_name='П')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='ЗМ')),
                ('missed_goals', models.PositiveSmallIntegerField(default=0, verbose_name='ПМ')),
                ('diff', models.PositiveSmallIntegerField(default=0, verbose_name='РМ')),
                ('point', models.PositiveSmallIntegerField(default=0, verbose_name='О')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Турнирная таблица',
                'verbose_name_plural': 'Турнирная таблица',
                'ordering': ['-point', 'club__name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.PositiveSmallIntegerField(null=True, verbose_name='Тур')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('finished', models.BooleanField(null=True, verbose_name='Завершено')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.club', verbose_name='Гости')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home', to='core.club', verbose_name='Хозяева')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['tour'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя игрока')),
                ('time', models.PositiveSmallIntegerField(default=0, verbose_name='Время гола')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.tour'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя игрока')),
                ('numb', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер игрока')),
                ('position', models.CharField(max_length=50, verbose_name='Позиция игрока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото игрока')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'unique_together': {('club', 'numb')},
            },
        ),
    ]
