# Generated by Django 4.1.7 on 2023-03-16 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Клуб')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='club-images/')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('title', models.CharField(max_length=500)),
                ('info', models.TextField()),
                ('interview_author', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Имя игрока')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия игрока')),
                ('numb', models.PositiveSmallIntegerField(verbose_name='Номер игрока')),
                ('gif', models.FileField(upload_to='media/gif', verbose_name='Gif игрока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image', verbose_name='Фото игрока')),
                ('like', models.BooleanField(blank=True, null=True)),
                ('dislike', models.BooleanField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'unique_together': {('club', 'numb')},
            },
        ),
        migrations.CreateModel(
            name='YellowCardsPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yellow_cards', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.PositiveSmallIntegerField(default=0, verbose_name='И')),
                ('win', models.PositiveSmallIntegerField(default=0, verbose_name='В')),
                ('draw', models.PositiveSmallIntegerField(default=0, verbose_name='Н')),
                ('lose', models.PositiveSmallIntegerField(default=0, verbose_name='П')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='ЗМ')),
                ('missed_goals', models.PositiveSmallIntegerField(default=0, verbose_name='ПМ')),
                ('diff', models.PositiveSmallIntegerField(default=0, verbose_name='РМ')),
                ('point', models.PositiveSmallIntegerField(default=0, verbose_name='О')),
                ('oxirgi_1', models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15)),
                ('oxirgi_2', models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15)),
                ('oxirgi_3', models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15)),
                ('oxirgi_4', models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15)),
                ('oxirgi_5', models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Турнирная таблица',
                'verbose_name_plural': 'Турнирная таблица',
                'ordering': ['-point'],
            },
        ),
        migrations.CreateModel(
            name='RedCardsPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_cards', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.PositiveSmallIntegerField(null=True, verbose_name='Тур')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('finished', models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=30, verbose_name='Завершено')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.club', verbose_name='Гости')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home', to='core.club', verbose_name='Хозяева')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GoalsPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plager_goal', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_point', models.PositiveSmallIntegerField(default=0, verbose_name='Счет хозяев')),
                ('guest_point', models.PositiveSmallIntegerField(default=0, verbose_name='Счет гостей')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('home_red_card', models.PositiveSmallIntegerField(default=0)),
                ('guest_red_card', models.PositiveSmallIntegerField(default=0)),
                ('home_yellow_card', models.PositiveSmallIntegerField(default=0)),
                ('guest_yellow_card', models.PositiveSmallIntegerField(default=0)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.matches')),
            ],
            options={
                'verbose_name': 'Отчет о матче',
                'verbose_name_plural': 'Отчет о матчи',
            },
        ),
        migrations.CreateModel(
            name='AboutPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст игрока')),
                ('yellow_cards', models.PositiveSmallIntegerField(verbose_name='Желтая карточка')),
                ('red_cards', models.PositiveSmallIntegerField(verbose_name='Красная карточка')),
                ('goals', models.PositiveBigIntegerField(verbose_name='Количество голов')),
                ('force', models.PositiveIntegerField(verbose_name='Сила')),
                ('technique', models.PositiveIntegerField(verbose_name='Техника')),
                ('pas', models.PositiveIntegerField(verbose_name='Пас')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'verbose_name': 'Об игроке',
                'verbose_name_plural': 'Об игроке',
            },
        ),
    ]
