# Generated by Django 3.2 on 2023-02-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='red_card',
            new_name='guest_red_card',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='yellow_card',
            new_name='guest_yellow_card',
        ),
        migrations.AddField(
            model_name='game',
            name='home_red_card',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_yellow_card',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
