# Generated by Django 4.1.7 on 2023-03-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalsplayer',
            options={'verbose_name': 'Бомбордиры', 'verbose_name_plural': 'Бомбордиры'},
        ),
        migrations.AlterModelOptions(
            name='redcardsplayer',
            options={'verbose_name': 'Красные карточки', 'verbose_name_plural': 'Красные карточки'},
        ),
        migrations.AlterModelOptions(
            name='yellowcardsplayer',
            options={'verbose_name': 'Желтые карточки', 'verbose_name_plural': 'Желтые карточки'},
        ),
        migrations.AlterField(
            model_name='matches',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.club', verbose_name='Гости'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='core.club', verbose_name='Хозяева'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='media/gif', verbose_name='Gif игрока'),
        ),
    ]
