# Generated by Django 4.1.7 on 2023-03-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.matches'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club', verbose_name='Гости'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='core.club', verbose_name='Хозяева'),
        ),
    ]
