# Generated by Django 3.2 on 2023-03-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230224_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Player',
        ),
    ]
