# Generated by Django 4.1.7 on 2023-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_game_tour_alter_matches_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='media/image', verbose_name='Фото игрока'),
        ),
    ]
