# Generated by Django 4.1.7 on 2023-03-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalsplayer',
            old_name='goals',
            new_name='counts',
        ),
    ]
