# Generated by Django 3.2 on 2023-02-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230223_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
