# Generated by Django 3.2 on 2023-03-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_player_numb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=1, max_length=70, verbose_name='Фамилия игрока'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AboutPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст игрока')),
                ('yellow_cards', models.PositiveSmallIntegerField(verbose_name='Желтая карточка')),
                ('red_cards', models.PositiveSmallIntegerField(verbose_name='Красная карточка')),
                ('goals', models.PositiveBigIntegerField(verbose_name='Количество голов')),
                ('force', models.PositiveIntegerField(verbose_name='Сила')),
                ('technique', models.PositiveIntegerField(verbose_name='Техника')),
                ('pas', models.PositiveIntegerField(verbose_name='Пас')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'verbose_name': 'Об игроке',
                'verbose_name_plural': 'Об игроке',
            },
        ),
    ]
