# Generated by Django 4.1.7 on 2023-04-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_goals_goalsplayer_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='dislike',
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palyer_club', to='core.club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
