# Generated by Django 3.2 on 2023-03-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230305_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='gif',
            field=models.FileField(default=1, upload_to='media/gif', verbose_name='Gif игрока'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image', verbose_name='Фото игрока'),
        ),
    ]
