# Generated by Django 3.2 on 2023-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230306_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, max_length=10, null=True, upload_to='media/image', verbose_name='Фото игрока'),
        ),
    ]
