# Generated by Django 4.1.7 on 2023-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_liketoplayer_remove_test_bought_remove_test_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liketoplayer',
            name='dislike_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liketoplayer',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
