# Generated by Django 3.2 on 2023-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttable',
            name='oxirgi_1',
            field=models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15),
        ),
        migrations.AddField(
            model_name='tournamenttable',
            name='oxirgi_2',
            field=models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15),
        ),
        migrations.AddField(
            model_name='tournamenttable',
            name='oxirgi_3',
            field=models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15),
        ),
        migrations.AddField(
            model_name='tournamenttable',
            name='oxirgi_4',
            field=models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15),
        ),
        migrations.AddField(
            model_name='tournamenttable',
            name='oxirgi_5',
            field=models.CharField(choices=[('Win', 'win'), ('Draw', 'draw'), ('Lose', 'lose')], default='Draw', max_length=15),
        ),
    ]
