# Generated by Django 4.1.7 on 2023-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_liketoplayer_dislike_count_liketoplayer_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutplayer',
            name='dislikes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutplayer',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LikeToPlayer',
        ),
    ]
