# Generated by Django 4.1.7 on 2023-04-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aboutplayer_dislikes_aboutplayer_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutplayer',
            old_name='dislikes',
            new_name='likes_count',
        ),
        migrations.RemoveField(
            model_name='aboutplayer',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, null=True)),
                ('aboutplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.aboutplayer')),
            ],
        ),
    ]
