# Generated by Django 3.2 on 2023-03-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_game_playergoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Отчет о матче', 'verbose_name_plural': 'Отчет о матчи'},
        ),
        migrations.RemoveField(
            model_name='playergoal',
            name='name',
        ),
        migrations.AddField(
            model_name='playergoal',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playergoal',
            name='time',
            field=models.DateTimeField(verbose_name='Время гола'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
