# Generated by Django 4.1.7 on 2023-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_dislikes_aboutplayer_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutplayer',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
