# Generated by Django 3.2 on 2023-03-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230309_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour',
            new_name='Matches',
        ),
        migrations.AlterModelOptions(
            name='tournamenttable',
            options={'ordering': ['-point'], 'verbose_name': 'Турнирная таблица', 'verbose_name_plural': 'Турнирная таблица'},
        ),
    ]
