# Generated by Django 4.1.7 on 2023-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aboutplayer_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophey',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='club',
            name='trophey',
        ),
        migrations.AddField(
            model_name='club',
            name='trophey',
            field=models.ManyToManyField(blank=True, null=True, to='core.trophey'),
        ),
    ]
