# Generated by Django 3.2 on 2023-03-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230309_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='date',
        ),
    ]
