# Generated by Django 3.2 on 2023-03-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_matches_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
