# Generated by Django 3.2 on 2023-03-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_matches_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['date'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
    ]
