# Generated by Django 4.1.7 on 2023-04-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_trophey_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophey',
            name='name',
        ),
    ]
