# Generated by Django 4.1.7 on 2023-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_trophey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophey',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
