# Generated by Django 4.1.7 on 2023-03-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_infomatch_delete_playergoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomatch',
            old_name='time',
            new_name='date',
        ),
    ]
