# Generated by Django 4.1.7 on 2023-03-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_time_infomatch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomatch',
            name='player_command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.club'),
            preserve_default=False,
        ),
    ]
