# Generated by Django 4.1.7 on 2023-03-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_infomatch_player_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plager_goal', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='RedCardsPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_cards', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='YellowCardsPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yellow_cards', to='core.player')),
            ],
        ),
        migrations.AlterField(
            model_name='matches',
            name='finished',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default=1, max_length=30, verbose_name='Завершено'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InfoMatch',
        ),
    ]
